/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controller.Controller;
import Controller.ProfessorController;
import Model.Conexion;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author USUARIO
 */
public class Credentials extends javax.swing.JFrame {
    
    
    
    private User ventanaUser; // Variable para almacenar la referencia de User

    
    Credentials.ImagePanel fondo = new Credentials.ImagePanel();
    /**
     * Creates new form Credentials
     */

    public Credentials(User ventanaUser) {
        this.ventanaUser = ventanaUser;
        this.setContentPane(fondo);
        initComponents();
        setLocationRelativeTo(null);
        setBackground(new java.awt.Color(0, 0, 0, 0));

                // Eliminar fondo de la caja de texto
        //        texto1.setBackground(new Color(0, 0, 0, 0));
        //        texto2.setBackground(new Color(0, 0, 0, 0));

        verClave.setBackground(new Color(0, 0, 0, 0));


        // Añadir espacion entre el borde y el texto
        texto1.setBorder(BorderFactory.createCompoundBorder(
                texto1.getBorder(), new EmptyBorder(5, 10, 5, 10)));
        texto2.setBorder(BorderFactory.createCompoundBorder(
                texto2.getBorder(), new EmptyBorder(5, 10, 5, 10)));
    }

    public Credentials() {
        
        this.setContentPane(fondo);
        initComponents();
        
        setLocationRelativeTo(null); // Centrar la ventana.
        
        // Bajar opacida de ventana
       
        // Eliminar auto enfoque


        // Cambiar diseño del boton
        // Eliminar efecto 3d
        boton1.setContentAreaFilled(false); // Elimina el color de fondo
        boton2.setContentAreaFilled(false);

        // Repinta
        boton1.setBackground(new Color(101, 22, 175));
        boton1.setOpaque(true);
        boton1.setBorderPainted(false);

        boton2.setBackground(new Color(50, 46, 60));
        boton2.setOpaque(true);
        boton2.setBorderPainted(false);
    }
    
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        texto1 = new javax.swing.JTextField();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        verClave = new javax.swing.JCheckBox();
        texto2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Entrar al panel");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Iniciar Sesión");

        texto1.setToolTipText("");
        texto1.setActionCommand("<Not Set>");
        texto1.setBorder(null);
        texto1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                texto1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                texto1FocusLost(evt);
            }
        });
        texto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto1ActionPerformed(evt);
            }
        });

        boton1.setBackground(new java.awt.Color(101, 22, 175));
        boton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boton1.setForeground(new java.awt.Color(255, 255, 255));
        boton1.setText("Ingresar");
        boton1.setBorder(null);
        boton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton1MouseClicked(evt);
            }
        });

        boton2.setBackground(new java.awt.Color(50, 46, 60));
        boton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boton2.setForeground(new java.awt.Color(255, 255, 255));
        boton2.setText("Cancelar");
        boton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 46, 60), 8));
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        verClave.setForeground(new java.awt.Color(255, 255, 255));
        verClave.setText("Ver Clave");
        verClave.setBorder(null);
        verClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verClaveActionPerformed(evt);
            }
        });

        texto2.setBorder(null);
        texto2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                texto2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                texto2FocusLost(evt);
            }
        });
        texto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(texto1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addComponent(boton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(texto2)
                        .addComponent(verClave, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto1ActionPerformed

    private void texto1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texto1FocusGained
//        if(texto1.getText().equals("Usuario")){
//            texto1.setText("");
//            texto1.setForeground(new Color(153,153,153));
//        }
    }//GEN-LAST:event_texto1FocusGained

    private void texto1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texto1FocusLost
//        if(texto1.getText().equals("")){
//            texto1.setText("Usuario");
//            texto1.setForeground(new Color(153,153,153));
//        }
    }//GEN-LAST:event_texto1FocusLost

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        dispose();
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseClicked
        String usuarioIngresado = texto1.getText();
        String passwordIngresada = new String(texto2.getPassword());

        Conexion conexion = new Conexion();
        Connection con = conexion.abrir();

        if (con != null) {
            try {

                String sql = "SELECT * FROM login WHERE username = ? AND passUser = PASSWORD(?)";
                PreparedStatement stmt = con.prepareStatement(sql);
                stmt.setString(1, usuarioIngresado);
                stmt.setString(2, passwordIngresada);
                ResultSet rs = stmt.executeQuery();

                if (rs.next()) {
                    // Usuario y contraseña correctos
                    if (usuarioIngresado.equals("admin")) {
                        ventanaUser.dispose();
                        Controller contro = new Controller();
                        contro.iniciar_admin();
                        dispose();
                    } else if (usuarioIngresado.equals("docente")) {
                        ventanaUser.dispose();
                        ProfessorController profeContro = new ProfessorController();
                        profeContro.iniciarProfessor();
                        dispose();
                    }else if (usuarioIngresado.equals("Ruben")) {
                        ventanaUser.dispose();
                        ProfessorController profeContro = new ProfessorController();
                        profeContro.iniciarProfessor();
                        dispose();
                    }else if (usuarioIngresado.equals("Angel")) {
                        ventanaUser.dispose();
                        ProfessorController profeContro = new ProfessorController();
                        profeContro.iniciarProfessor();
                        dispose();
                    }}
                 else {
                    JOptionPane.showMessageDialog(this, "Usuario o Contraseña Incorrecta");
                }

                rs.close();
                stmt.close();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos");
            } 
        } 
        

//        String usuarioAdmin = "admin";
//        String contraAdmin = "123";
//        String usuarioDocente = "docente";
//        String contraDocente = "456";
//
//
//        String usuarioIngresado = texto1.getText();
//        String passwordIngresada = new String(texto2.getPassword());
// 
//        if(usuarioIngresado.equals(usuarioAdmin) && passwordIngresada.equals(contraAdmin)){
//            ventanaUser.dispose();
//            Controller contro = new Controller();
//            contro.iniciar_admin();
//            dispose();
//        }
//        else if(usuarioIngresado.equals(usuarioDocente) && passwordIngresada.equals(contraDocente)){
//            ventanaUser.dispose();
//            ProfessorController profeContro = new ProfessorController();
//            profeContro.iniciarProfessor();
//            dispose();
//        }
//        else{
//            JOptionPane.showMessageDialog(this, "Usuario o Contraseña Incorrecta");
//        }
    }//GEN-LAST:event_boton1MouseClicked

    private void verClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verClaveActionPerformed
        if(verClave.isSelected()){
            texto2.setEchoChar((char)0);
        }else{
            texto2.setEchoChar('*');
        }
    }//GEN-LAST:event_verClaveActionPerformed

    private void texto2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texto2FocusGained
//        if(texto2.getText().equals("Contraseña")){
//            texto2.setText("");
//            texto2.setForeground(new Color(153,153,153));
//        }
    }//GEN-LAST:event_texto2FocusGained

    private void texto2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texto2FocusLost
//        if(texto2.getText().equals("")){
//            texto2.setText("Contraseña");
//            texto2.setForeground(new Color(153,153,153));
//        }
    }//GEN-LAST:event_texto2FocusLost

    private void texto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credentials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credentials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credentials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credentials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credentials().setVisible(true);
            }
        });
    }
    
    public class ImagePanel extends JPanel {
        private Image image;

        public ImagePanel() {
            image = new ImageIcon(getClass().getResource("/Images/fondo.png")).getImage();
            setOpaque(false); // Asegura que el panel sea transparente.
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            
            if (image != null) {
                Graphics2D g2d = (Graphics2D) g.create();
                // Aplica opacidad al fondo.
                g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.8f));
                g2d.drawImage(image, 0, 0, getWidth(), getHeight(), this);
                g2d.dispose();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton1;
    public javax.swing.JButton boton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField texto1;
    private javax.swing.JPasswordField texto2;
    private javax.swing.JCheckBox verClave;
    // End of variables declaration//GEN-END:variables
    private Init.ImagePanel imagePanel;
}
